# Generated by Django 5.2.13 on 2026-04-17 06:46

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batterybrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batterybrand', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Batteryprice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bprice', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bprice', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tyrebrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tyrebrand', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_director', models.BooleanField(default=True)),
                ('is_battery', models.BooleanField(default=True)),
                ('is_tyre', models.BooleanField(default=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('department', models.CharField(choices=[('Administration', 'Administration'), ('Battery', 'Battery'), ('Tyre', 'Tyre'), ('Records', 'Records')], default=True, max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=50, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('departuredate', models.CharField(blank=True, max_length=25, null=True, verbose_name='End Date e.g (01/02/2024)')),
                ('car_brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='Car brand')),
                ('cparktype', models.CharField(blank=True, choices=[('LONGER', 'LONGER'), ('REPAIR', 'REPAIR'), ('DAY', 'DAY'), ('NIGHT', 'NIGHT')], default='LEAVE', max_length=30, null=True, verbose_name='Parking Type')),
                ('customer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Customer Name')),
                ('customerNiN', models.CharField(blank=True, max_length=255, null=True, verbose_name='Customer NIN')),
                ('cnumberplate', models.CharField(blank=True, max_length=255, null=True, verbose_name='Car number plate')),
                ('color', models.CharField(blank=True, max_length=255, null=True, verbose_name='Color of the car')),
                ('p_status', models.CharField(blank=True, choices=[('TAKEN', 'TAKEN'), ('AVAILABLE', 'AVAILABLE'), ('PENDING', 'PENDING')], default='Taken', max_length=30, null=True, verbose_name='Status of the car at parking')),
                ('fee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nyondoapp.price', verbose_name='Parking fee e.g 1000')),
            ],
        ),
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('decription', models.CharField(blank=True, max_length=250, null=True, verbose_name='Any other details')),
                ('voltage', models.CharField(blank=True, max_length=255, null=True, verbose_name='Battery voltage')),
                ('customer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Serial number')),
                ('batery_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nyondoapp.batterybrand', verbose_name='Battery brand')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nyondoapp.price', verbose_name='Battery price')),
            ],
        ),
        migrations.CreateModel(
            name='Tyre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('decription', models.CharField(blank=True, max_length=250, null=True, verbose_name='Any other details')),
                ('size', models.CharField(blank=True, max_length=255, null=True, verbose_name='tyre size')),
                ('customer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Serial number')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nyondoapp.price', verbose_name='Tyre price')),
                ('tyre_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nyondoapp.tyrebrand', verbose_name='Tyre brand')),
            ],
        ),
    ]
