# Generated by Django 5.2.13 on 2026-04-17 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tyre',
            name='other',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Other Tyre Service'),
        ),
        migrations.AlterField(
            model_name='battery',
            name='voltage',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Battery model'),
        ),
    ]
