# Generated by Django 5.2.13 on 2026-04-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondoapp', '0002_tyre_other_alter_battery_voltage'),
    ]

    operations = [
        migrations.AddField(
            model_name='battery',
            name='qty',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Item Quantity'),
        ),
    ]
