# Generated by Django 5.2.13 on 2026-04-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondoapp', '0003_battery_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='tyre',
            name='qty',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Item Quantity'),
        ),
    ]
