# Generated by Django 5.2.13 on 2026-04-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondoapp', '0004_tyre_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_car',
            field=models.BooleanField(default=True),
        ),
    ]
