# Generated by Django 5.2.13 on 2026-04-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondoapp', '0006_remove_car_created_at_remove_car_departuredate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
