# Generated by Django 5.2.13 on 2026-04-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondoapp', '0007_car_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='bprice',
            field=models.IntegerField(default=2000),
        ),
    ]
