# Generated by Django 5.2.13 on 2026-04-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondoapp', '0008_alter_price_bprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='bprice',
            field=models.CharField(max_length=200),
        ),
    ]
