# Generated by Django 5.2.13 on 2026-04-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondoapp', '0009_alter_price_bprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='tyre',
            name='serial',
            field=models.CharField(default='xvyz12321', max_length=255, verbose_name='Serial number'),
        ),
        migrations.AlterField(
            model_name='tyre',
            name='customer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Customer Name'),
        ),
    ]
