# Generated by Django 5.2.13 on 2026-04-18 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nyondoapp', '0010_tyre_serial_alter_tyre_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tyre',
            name='other',
        ),
    ]
