# Generated by Django 5.2.13 on 2026-04-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondoapp', '0011_remove_tyre_other'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tprice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tprice', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Batteryprice',
        ),
        migrations.AlterField(
            model_name='tyre',
            name='size',
            field=models.CharField(default=0.001520158625247852, max_length=255, verbose_name='tyre size'),
            preserve_default=False,
        ),
    ]
