# Generated by Django 5.2.13 on 2026-04-19 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondoapp', '0012_tprice_delete_batteryprice_alter_tyre_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='cparkpaymode',
            field=models.CharField(blank=True, choices=[('CASH', 'CASH'), ('MM', 'MM')], default='CASH', max_length=30, null=True, verbose_name='Parking Payment Mode'),
        ),
        migrations.AddField(
            model_name='car',
            name='cparkv',
            field=models.CharField(blank=True, choices=[('NO', 'NO'), ('YES', 'YES')], default='NO', max_length=30, null=True, verbose_name='Have you verified?'),
        ),
        migrations.AlterField(
            model_name='tyre',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nyondoapp.tprice', verbose_name='Tyre price'),
        ),
    ]
