# Generated by Django 6.0.2 on 2026-04-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondoapp', '0013_car_cparkpaymode_car_cparkv_alter_tyre_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pressure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Customer Name')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price (UGX)')),
                ('qty', models.CharField(blank=True, max_length=50, null=True, verbose_name='Quantity')),
                ('cnumberplate', models.CharField(blank=True, max_length=100, null=True, verbose_name='Car Number Plate')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Any other details')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Puncture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Customer Name')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price (UGX)')),
                ('qty', models.CharField(blank=True, max_length=50, null=True, verbose_name='Quantity')),
                ('cnumberplate', models.CharField(blank=True, max_length=100, null=True, verbose_name='Car Number Plate')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Any other details')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Valve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Customer Name')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price (UGX)')),
                ('qty', models.CharField(blank=True, max_length=50, null=True, verbose_name='Quantity')),
                ('cnumberplate', models.CharField(blank=True, max_length=100, null=True, verbose_name='Car Number Plate')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Any other details')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
