# Generated by Django 6.0.2 on 2026-04-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondoapp', '0014_pressure_puncture_valve'),
    ]

    operations = [
        migrations.AddField(
            model_name='battery',
            name='transaction_type',
            field=models.CharField(choices=[('SOLD', 'Sold'), ('HIRED', 'Hired')], default='SOLD', max_length=10, verbose_name='Transaction Type'),
        ),
    ]
