# Generated by Django 6.0.2 on 2026-04-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondoapp', '0015_battery_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='battery',
            name='payment_mode',
            field=models.CharField(choices=[('CASH', 'Cash'), ('MM', 'Mobile Money')], default='CASH', max_length=20, verbose_name='Payment Mode'),
        ),
        migrations.AlterField(
            model_name='battery',
            name='customer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Customer Name'),
        ),
    ]
