# Generated by Django 6.0.2 on 2026-04-23 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondoapp', '0016_battery_payment_mode_alter_battery_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='cparktype',
            field=models.CharField(blank=True, choices=[('TRUCK', 'Truck'), ('PERSONAL CAR', 'Personal Car'), ('TAXI', 'Taxi'), ('COASTER', 'Coaster'), ('BODA-BODA', 'Boda-boda')], default='PERSONAL CAR', max_length=30, null=True, verbose_name='Vehicle Type'),
        ),
        migrations.AlterField(
            model_name='car',
            name='p_status',
            field=models.CharField(blank=True, choices=[('TAKEN', 'TAKEN'), ('AVAILABLE', 'AVAILABLE'), ('PENDING', 'PENDING')], default='TAKEN', max_length=30, null=True, verbose_name='Status of the car at parking'),
        ),
    ]
