# Generated by Django 6.0.2 on 2026-04-24 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondoapp', '0017_alter_car_cparktype_alter_car_p_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='car',
            name='sign_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_brand',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Car Brand'),
        ),
        migrations.AlterField(
            model_name='car',
            name='cnumberplate',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Car Number Plate'),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Color of the Car'),
        ),
        migrations.AlterField(
            model_name='car',
            name='customer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Driver First Name'),
        ),
        migrations.AlterField(
            model_name='car',
            name='customerv',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Driver Other Name'),
        ),
        migrations.AlterField(
            model_name='car',
            name='fee',
            field=models.IntegerField(blank=True, null=True, verbose_name='Parking Fee (UGX)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='p_status',
            field=models.CharField(blank=True, choices=[('TAKEN', 'TAKEN'), ('AVAILABLE', 'AVAILABLE'), ('PENDING', 'PENDING')], default='TAKEN', max_length=30, null=True, verbose_name='Status of the Car at Parking'),
        ),
    ]
