# Generated by Django 6.0.2 on 2026-04-24 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondoapp', '0018_car_phone_car_sign_out_time_alter_car_car_brand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='Slot Number')),
                ('status', models.CharField(choices=[('FREE', 'Free'), ('OCCUPIED', 'Occupied')], default='FREE', max_length=10, verbose_name='Slot Status')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.AlterField(
            model_name='car',
            name='p_status',
            field=models.CharField(blank=True, choices=[('PARKED', 'Parked'), ('COLLECTED', 'Collected'), ('OVERDUE', 'Overdue')], default='PARKED', max_length=10, null=True, verbose_name='Car Status'),
        ),
        migrations.AlterField(
            model_name='tyre',
            name='size',
            field=models.CharField(max_length=255, verbose_name='Tyre size'),
        ),
        migrations.AddField(
            model_name='car',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nyondoapp.parkingslot', verbose_name='Parking Slot'),
        ),
    ]
