# Generated by Django 6.0.2 on 2026-04-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondoapp', '0019_parkingslot_alter_car_p_status_alter_tyre_size_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pressure',
        ),
        migrations.DeleteModel(
            name='Puncture',
        ),
        migrations.DeleteModel(
            name='Valve',
        ),
        migrations.AddField(
            model_name='tyre',
            name='payment_mode',
            field=models.CharField(choices=[('CASH', 'Cash'), ('MM', 'Mobile Money')], default='CASH', max_length=20, verbose_name='Payment Mode'),
        ),
        migrations.AlterField(
            model_name='tyre',
            name='qty',
            field=models.CharField(default=1, max_length=255, verbose_name='Item Quantity'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tyre',
            name='serial',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Serial number'),
        ),
    ]
