# Generated by Django 6.0.2 on 2026-04-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondoapp', '0020_delete_pressure_delete_puncture_delete_valve_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battery',
            name='voltage',
            field=models.CharField(default=1, max_length=255, verbose_name='Battery model'),
            preserve_default=False,
        ),
    ]
