# Generated by Django 6.0.2 on 2026-04-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondoapp', '0021_alter_battery_voltage'),
    ]

    operations = [
        migrations.AddField(
            model_name='battery',
            name='bmodel',
            field=models.CharField(default=1, max_length=255, verbose_name='Battery Model (e.g. nz70)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='battery',
            name='voltage',
            field=models.CharField(max_length=255, verbose_name='Battery Voltage (e.g. 12V)'),
        ),
    ]
